Sou Apoiador - Página para Cadastro [Backend]
SouJunior/site-backend pull request #2
Opened 2023-04-18 12:06 UTC by lucasmbrute2

US referente: 

- https://github.com/SouJunior/products/issues/50

Criar um endpoint que receba os dados do formulário e envie um e-mail.

Os dados do usuário deverão ser direcionados para o e-mail do "Brandão"; [[wouerner@soujunior.tech](mailto:wouerner@soujunior.tech)]

2023-04-18 14:37 UTC, wandersonDeve requested changes

2023-04-18 14:37 UTC, wandersonDeve commented on src/modules/sponsor/tests/send-mail-to-new-donator.spec.ts
> +import { Test } from "@nestjs/testing"
Todos os testes dentro da pasta tests que esta na raiz do projeto, seguindo a mesma estrutura da pasta SRC

2023-04-18 14:37 UTC, wandersonDeve commented on src/shared/providers/mailer/tests/mailer-provider.spec.ts
> +import { Test } from "@nestjs/testing"
Todos os testes dentro da pasta tests que esta na raiz do projeto, seguindo a mesma estrutura da pasta SRC

2023-04-19 03:02 UTC, lucasmbrute2 commented on src/modules/sponsor/sponsor.controller.ts
> +    status: 200
não tem retorno então coloquei o type void mesmo.

2023-04-19 03:02 UTC, lucasmbrute2 commented on src/modules/sponsor/tests/send-mail-to-new-donator.spec.ts
> +import { Test } from "@nestjs/testing"
ok

2023-04-19 03:02 UTC, lucasmbrute2 commented on src/modules/sponsor/use-cases/__mocks__/send-mail-to-new-donator.ts
> +export const SendMailToNewSponsorUseCase = jest.fn().mockReturnValue({
ok

2023-04-19 03:02 UTC, lucasmbrute2 commented on src/shared/providers/mailer/tests/mailer-provider.spec.ts
> +import { Test } from "@nestjs/testing"
ok

2023-04-19 12:48 UTC, wandersonDeve approved these changes

2023-04-19 12:48 UTC, merged

2023-10-09 23:19 UTC, sabrinamir commented
@Paru369 estamos com este card parado aguardando testes. Você pode verificar quem da sua equipe irá tocar?